image: pythondiscord/site-ci:latest

variables:
  RABBITMQ_HOST: rabbit
  RETHINKDB_HOST: rethinkdb

stages:
  - test
  - deploy

test:
  tags:
  - docker

  stage: test
  services:
    - name: rabbitmq:3.7.5-alpine
      alias: rabbit

    - name: rethinkdb:2.3.6
      alias: rethinkdb

  cache:
    paths:
      - ".venv"
      - ".gem"

  script:
    - pipenv sync --dev
    - pipenv run lint
    - pipenv run lintscss
    - pipenv run python gunicorn_config.py
    - pipenv run test

deploy:
  tags:
  - docker

  only:
  - master

  services:
    - docker:dind

  stage: deploy
  script:
    - sh scripts/deploy.sh

  environment:
    name: Production
    url: https://pythondiscord.com
