language: python
python:
  - "3.6"

addons:
  rethinkdb: "2.3"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt
script:
  - flake8
  - py.test app_test.py --cov pysite --cov-report term-missing -v
  - coveralls
after_success:
  - python deploy.py
