language: python
python:
  - "3.6"

addons:
  rethinkdb: "2.3"

branches:
  only:
    - "master"

sudo: required

services:
  - docker
  - rabbitmq

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - RABBITMQ_HOST=localhost

install:
  - pip install pipenv
  - pipenv sync --dev --three
  - gem install scss_lint
script:
  - pipenv run lint
  - pipenv run python gunicorn_config.py
  - pipenv run test
#  - pipenv run coveralls
  - scss-lint scss/pysite
after_success:
  - bash scripts/deploy.sh

cache: pip

notifications:
  email: false
