language: python
python:
  - "3.6"

addons:
  rethinkdb: "2.3"

branches:
  only:
    - "master"

env:
  - FLASK_DEBUG=1

install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt
script:
  - flake8
  - python gunicorn_config.py
  - py.test app_test.py --cov pysite --cov-report term-missing -v
  - coveralls
after_success:
  - python deploy.py

cache: pip

notifications:
  email: false
